//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeometryTest
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeometriesTest.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfPoint xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Point&gt;
        ///    &lt;X&gt;-323&lt;/X&gt;
        ///    &lt;Y&gt;0&lt;/Y&gt;
        ///  &lt;/Point&gt;
        ///  &lt;Point&gt;
        ///    &lt;X&gt;-137&lt;/X&gt;
        ///    &lt;Y&gt;-116&lt;/Y&gt;
        ///  &lt;/Point&gt;
        ///  &lt;Point&gt;
        ///    &lt;X&gt;72&lt;/X&gt;
        ///    &lt;Y&gt;19&lt;/Y&gt;
        ///  &lt;/Point&gt;
        ///  &lt;Point&gt;
        ///    &lt;X&gt;-166&lt;/X&gt;
        ///    &lt;Y&gt;146&lt;/Y&gt;
        ///  &lt;/Point&gt;
        ///&lt;/ArrayOfPoint&gt;.
        /// </summary>
        internal static string clip1 {
            get {
                return ResourceManager.GetString("clip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfArrayOfPoint xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;ArrayOfPoint&gt;
        ///    &lt;Point&gt;
        ///      &lt;X&gt;-34.087940510830911&lt;/X&gt;
        ///      &lt;Y&gt;-49.525703200775943&lt;/Y&gt;
        ///    &lt;/Point&gt;
        ///    &lt;Point&gt;
        ///      &lt;X&gt;-203&lt;/X&gt;
        ///      &lt;Y&gt;29&lt;/Y&gt;
        ///    &lt;/Point&gt;
        ///    &lt;Point&gt;
        ///      &lt;X&gt;-235.64733824032865&lt;/X&gt;
        ///      &lt;Y&gt;-54.478004108182127&lt;/Y&gt;
        ///    &lt;/Point&gt;
        ///    &lt;Point&gt;
        ///      &lt;X&gt;-137&lt;/X&gt;
        ///      &lt;Y&gt;-116&lt;/Y&gt;
        ///    &lt;/Point&gt;
        ///  &lt;/ArrayOfPoi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string result1 {
            get {
                return ResourceManager.GetString("result1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfPoint xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Point&gt;
        ///    &lt;X&gt;-282&lt;/X&gt;
        ///    &lt;Y&gt;-173&lt;/Y&gt;
        ///  &lt;/Point&gt;
        ///  &lt;Point&gt;
        ///    &lt;X&gt;-22&lt;/X&gt;
        ///    &lt;Y&gt;-271&lt;/Y&gt;
        ///  &lt;/Point&gt;
        ///  &lt;Point&gt;
        ///    &lt;X&gt;210&lt;/X&gt;
        ///    &lt;Y&gt;-163&lt;/Y&gt;
        ///  &lt;/Point&gt;
        ///  &lt;Point&gt;
        ///    &lt;X&gt;-203&lt;/X&gt;
        ///    &lt;Y&gt;29&lt;/Y&gt;
        ///  &lt;/Point&gt;
        ///&lt;/ArrayOfPoint&gt;.
        /// </summary>
        internal static string subject1 {
            get {
                return ResourceManager.GetString("subject1", resourceCulture);
            }
        }
    }
}
